In [1]:
!pip list

Package                   Version
------------------------- -----------
anyio                     4.12.1
appnope                   1.0.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.2
async-lru                 2.0.5
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.2.0
certifi                   2026.7.22
cffi                      2.0.0
charset-normalizer        3.5.1
comm                      0.2.3
debugpy                   1.8.21
decorator                 5.3.1
defusedxml                0.7.1
exceptiongroup            1.3.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.6.0
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.20
importlib_metadata        8.7.1
ipykernel                 6.31.0
ipython                   8.18.1
ipywidgets                8.1.9
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
json5                     0.15.0
jsonpointer               3.0.0
jsonschema                4.25.1
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_client            8.6.3
jupyter-console           6.6.3
jupyter_core              5.8.1
jupyter-events            0.12.1
jupyter-lsp               2.3.1
jupyter_server            2.18.2
jupyter_server_terminals  0.5.4
jupyterlab                4.5.11
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.17
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib-inline         0.2.2
mistune                   3.3.4
nbclient                  0.10.2
nbconvert                 7.17.1
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.5.7
notebook_shim             0.2.4
numpy                     2.0.2
overrides                 7.7.0
packaging                 26.3
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.7
pexpect                   4.9.0
pip                       26.0.1
platformdirs              4.4.0
prometheus_client         0.26.0
prompt_toolkit            3.0.52
psutil                    7.2.2
ptyprocess                0.7.0
pure_eval                 0.2.4
pycparser                 2.23
Pygments                  2.21.0
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
pytz                      2026.4
PyYAML                    6.0.3
pyzmq                     27.2.0
referencing               0.36.2
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.27.1
Send2Trash                2.1.0
setuptools                58.0.4
six                       1.17.0
soupsieve                 2.8.4
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.4.0
tomli                     2.4.1
tornado                   6.5.10
traitlets                 5.15.1
typing_extensions         4.16.0
tzdata                    2026.4
uri-template              1.3.0
urllib3                   2.6.3
wcwidth                   0.9.1
webcolors                 24.11.1
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.16
zipp                      3.23.1

In [2]:
!pip freeze > requirements.txt

In [3]:
!ls

requirements.txt Untitled.ipynb

In [4]:
import pandas as pd

In [8]:
pd.__version__

'2.3.3'

In [5]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

In [6]:
df = pd.read_csv(url)

In [7]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [9]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [10]:
fuel_types = set(df["fuel_type"])

In [11]:
print(fuel_types)

{'Hybrid', 'Gasoline', 'Diesel'}

In [12]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [13]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [14]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [15]:
horsepower_median = df["horsepower"].median()

In [16]:
print(horsepower_median)

254.0